exports.seed = async function (knex) {
  // Deletes ALL existing entries
  await knex('report').del()
  await knex('report').insert([
    {
      id: 1,
      house_address_id: '393-Wairau-Road-Totara-Vale-Auckland-0629',
      date_submitted: '22092022',
      report_submitter: 'renter',
      status: 'Approved',
      address: '393 Wairau Road, Auckland',
      email: 'fredpene@hotmail.co.nz',
      current_rent: '850',
      bond: '',
      rent_advance: '',
      start_date: '12062021',
      occupancy: '5',
      pets_cats: '0',
      pets_dogs: '0',
      garden:
        'big fuck off lawn on a vicious incline (not fun to mow), surrounded by bush, garden bed on lawn',
      home_health_insulation_ceiling: '1',
      home_health_insulation_floor: '',
      home_health_insulation_wall: '1',
      home_health_extractor_fan: '1',
      home_health_rangehood: '1',
      security_system: '0',
      heating: '{heat pump}',
      ventilation_system: '1',
      fire_alarms: '1',
      double_glazed: '0',
      neighborhood_noise: 'No',
      rate_home_health: '3',
      energy_sources: 'LPG, Mains Electric',
      water_tank: '0',
      composting_system: '0',
      rate_property_manager: '4',
      rate_property_manager_responsiveness: '4',
      other_comments:
        'front door has a gap at the bottom causing a bad draught in the winter, downstairs bathroom fan extractor is shit so i use a dehumidifier instead',
    },
    {
      id: 2,
      house_address_id: '148-Howe-Street-Freemans-Bay-Auckland-1011',
      date_submitted: '23092022',
      report_submitter: 'renter',
      status: 'Approved',
      address: '16/148 Howe Street Freemans Bay, Auckland 1011',
      email: 'karlbayly@gmail.com',
      current_rent: '750',
      bond: '3000',
      rent_advance: '1500',
      start_date: '01042021',
      occupancy: '3',
      pets_cats: '0',
      pets_dogs: '0',
      garden: 'Non',
      home_health_insulation_ceiling: '',
      home_health_insulation_floor: '',
      home_health_insulation_wall: '',
      home_health_extractor_fan: '1',
      home_health_rangehood: '1',
      security_system: '0',
      heating: '{Heat pump}',
      ventilation_system: '0',
      fire_alarms: '1',
      double_glazed: '0',
      neighborhood_noise: 'No',
      rate_home_health: '3',
      energy_sources: 'Grid Electricty',
      water_tank: '0',
      composting_system: '1',
      rate_property_manager: '3',
      rate_property_manager_responsiveness: '3',
      other_comments: '',
    },
    {
      id: 3,
      house_address_id: '31-Walters-Road-Mount-Eden-Auckland-1024',
      date_submitted: '23092022',
      report_submitter: 'renter',
      status: 'Approved',
      address: '31 Walters Road, Mount Eden, 1024, New Zealand',
      email: 'fergus.haywood5@gmail.com',
      current_rent: '250',
      bond: '1000',
      rent_advance: '500',
      start_date: '24032022',
      occupancy: '7',
      pets_cats: '0',
      pets_dogs: '0',
      garden: 'We have a garden and backyard',
      home_health_insulation_ceiling: '',
      home_health_insulation_floor: '1',
      home_health_insulation_wall: '1',
      home_health_extractor_fan: '1',
      home_health_rangehood: '1',
      security_system: '1',
      heating: 'HRV throughout house, central heating',
      ventilation_system: '1',
      fire_alarms: '',
      double_glazed: '1',
      neighborhood_noise:
        'We live next to Eden Park, when there are games on there is a lot of noise.',
      rate_home_health: '5',
      energy_sources: 'Solar, Electric Mains, Gas',
      water_tank: '',
      composting_system: '1',
      rate_property_manager: '5',
      rate_property_manager_responsiveness: '5',
      other_comments:
        'Our landlord quite often comes over with very little warning, we know this is techincally wrong and they need to give us more time but most of the time it is for the improvement of the house, and we dont really care that they come over with small amount of warning.',
    },
    {
      id: 4,
      house_address_id: '52-Nikau-Road-Otahuhu-Auckland-1062',
      date_submitted: '22092022',
      status: 'Approved',
      report_submitter: 'owner',
      address: '52 Nikau Road, Otahuhu',
      email: 'mikeshpatel39@gmail.com',
      current_rent: '620',
      bond: '0',
      rent_advance: '0',
      start_date: '20122020',
      occupancy: '4',
      pets_cats: '0',
      pets_dogs: '0',
      garden: '4 garden beds, many fruit trees',
      home_health_insulation_ceiling: '1',
      home_health_insulation_floor: '1',
      home_health_insulation_wall: '1',
      home_health_extractor_fan: '0',
      home_health_rangehood: '0',
      security_system: '0',
      heating: '{heat pump}',
      ventilation_system: '1',
      fire_alarms: '1',
      double_glazed: '1',
      neighborhood_noise: 'No',
      energy_sources: '{mains gas, mains electric}',
      water_tank: '0',
      composting_system: '1',
      other_comments: '',
    },
    {
      id: 5,
      house_address_id: '15A-Schopolo-Place-Albany-0632',
      date_submitted: '24092022',
      status: 'Approved',
      report_submitter: 'owner',
      address: '15A Schopolo Place, Albany',
      email: 'mikeshpatel39@gmail.com',
      current_rent: '400',
      bond: '0',
      rent_advance: '0',
      start_date: '20122020',
      occupancy: '1',
      pets_cats: '0',
      pets_dogs: '0',
      garden: 'Some plants off driveway, limited space',
      home_health_insulation_ceiling: '1',
      home_health_insulation_floor: '1',
      home_health_insulation_wall: '1',
      home_health_extractor_fan: '1',
      home_health_rangehood: '1',
      security_system: '0',
      heating: '{heat pump}',
      ventilation_system: '0',
      fire_alarms: '1',
      double_glazed: '1',
      neighborhood_noise: 'No',
      energy_sources: 'Mains Gas, Mains Electric',
      water_tank: '0',
      composting_system: '0',
      other_comments: '',
    },
    {
      id: 6,
      house_address_id: '15-Range-View-Road-Mount-Albert-1025',
      date_submitted: '26092022',
      status: 'pending',
      report_submitter: 'renter',
      address: '15 Range View Road, Mount Albert',
      email: 'sophiaroselawler@gmail.com',
      current_rent: '650',
      bond: '1950',
      rent_advance: '1300',
      start_date: '01052021',
      occupancy: '3',
      pets_cats: '1',
      pets_dogs: '1',
      garden:
        'Nice garden, landlord mows the lawns, allowed to make a vege patch!',
      home_health_insulation_ceiling: '1',
      home_health_insulation_floor: '1',
      home_health_insulation_wall: '0',
      home_health_extractor_fan: '1',
      home_health_rangehood: '0',
      security_system: '1',
      heating: 'heat pump',
      ventilation_system: '0',
      fire_alarms: '1',
      double_glazed: '0',
      neighborhood_noise:
        'There is mass construction all over the street! Next door there are apartment blocks being built and its very very noisy.',
      rate_home_health: '4',
      energy_sources: 'Mains, Electric',
      water_tank: '0',
      composting_system: '1',
      rate_property_manager: '3',
      rate_property_manager_responsiveness: '4',
      other_comments: `Landlord is pretty fucked. He's prompt and gets shit done but his general banter suckssss. He is very classist and always makes comments about the state housing being built. Was also very suss about the construction playing it off as minor when it was major. Calls some of the neighbours who are POC 'dodgy'`,
    },
    {
      id: 7,
      house_address_id: '38-Tyrico-Close-Unsworth-Heights-0632',
      date_submitted: '26092022',
      status: 'pending',
      report_submitter: 'renter',
      address: '38 Tyrico Close, Unsworth Heights',
      email: 'cmwsmart@gmail.com',
      current_rent: '210',
      bond: '420',
      rent_advance: '420',
      start_date: '02102017',
      occupancy: '3',
      pets_cats: '1',
      pets_dogs: '1',
      garden:
        'no backyard but weird garden area around the house - no fencing around the house',
      home_health_insulation_ceiling: '0',
      home_health_insulation_floor: '0',
      home_health_insulation_wall: '0',
      home_health_extractor_fan: '1',
      home_health_rangehood: '1',
      security_system: '0',
      heating: '{ }',
      ventilation_system: '0',
      fire_alarms: '1',
      double_glazed: '0',
      neighborhood_noise:
        'no but the landlord was doing renovations on the house which was loud early in the mornings on weekends',
      rate_home_health: '4',
      energy_sources: 'Mains Gas, Mains Electric',
      water_tank: '0',
      composting_system: '0',
      rate_property_manager: '3',
      rate_property_manager_responsiveness: '3',
      other_comments:
        'landlord lived below the property so would respond to things quickly but often had odd solutions instead of actually fixing things. He also had a lot boats on the property',
    },
  ])
}
